project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"

website:
  title: "git in 20 minutes"
  site-url: "https://github.com/mjgreen/git-in-20-minutes/"
  description: "training sessions in git et al"
  #favicon: img/logo.png
  google-analytics: "G-VJ3TCXTLSH"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mjgreen/git-in-20-minutes/
      - icon: rss
        href: index.xml

format:
  html:
    date-format: long
    theme:
      default
      #cosmo
      #light: flatly
      #dark: darkly
    css: styles.css
    



