---
title: "git in 20 minutes"
subtitle: "open science tools"
author: "Matt Green"
date: "2023/3/8"
date-format: "MMMM D, YYYY"
format:
  revealjs: 
    output-dir: docs
    menu: true
    progress: true
    slide-number: true
    chalkboard: 
      buttons: true
    preview-links: auto
    multiplex: false
    logo: images/GitHub-logo.png
    css: styles.css
    footer: <https://mjgreen.github.io/git-in-20-minutes>
engine: knitr
---

## Hello, There

This presentation will tell you a bit about git

## Orientation

The difference between git and github

::::: {.columns}

:::: {.column width="50%"}
::: {.middle}
**git**
:::
* git is a scvcs
* <u><em><b>S</b></em></u>ource  
  <u><em><b>C</b></em></u>ode  
  <u><em><b>V</b></em></u>ersion  
  <u><em><b>C</b></em></u>ontrol  
  <u><em><b>S</b></em></u>ystem
::::
:::: {.column width="50%"}
::: {.middle}
**github**
:::
* github.com is a website that stores git-generated stuff ...
* ... in the same way that OneDrive stores stuff generated by MS Office
::::

:::::

## Features 1/2

* remote backup to github.com is like onedrive except *you* control when it syncs
* time travel concept like apple time machine except *you* say what counts as an entry
* version control but better than naming files after the version they represent
* branching 
* collaboration using pull requests 

## Features 2/2
* diffs
* gitkraken
* facilitates working on multiple machines
* easy websites with github pages
* distribute files (e.g., supplementary materials for a journal article)

## Cons
* can't see inside docx and xlsx 

## recommended tools
* github desktop
* vscode (true plain text editor)
